<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <!-- Project is not a test project -->
    <SonarQubeTestProject>false</SonarQubeTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="VirtoCommerce.CustomerModule.Core" Version="3.1028.0" />
    <PackageReference Include="VirtoCommerce.OrdersModule.Data" Version="3.1018.0" />
    <PackageReference Include="VirtoCommerce.Platform.Data" Version="3.1076.0" />
    <PackageReference Include="VirtoCommerce.StoreModule.Core" Version="3.1009.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VirtoCommerce.XFrontend.Core\VirtoCommerce.XFrontend.Core.csproj" />
  </ItemGroup>
</Project>
